dist: xenial
sudo: false
services:
  - xvfb
branches:
  only:
    - master
before_script:
  - export DISPLAY=:99.0
script:
  - test/bin/sign_test.sh
notifications:
  email:
    on_success: never
    on_failure: change
addons:
  apt:
    packages:
      - xsel
