sudo: false
branches:
  only:
    - master
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start
script:
  - test/bin/sign_test.sh
notifications:
  email:
    on_success: never
    on_failure: change
addons:
  apt:
    packages:
      - xsel
